# Generated by Django 6.0.4 on 2026-04-20 01:01
# Corregido: db_column alineados exactamente al script SQLQueryProvitDER.sql

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        # ── ROL ──────────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol',  models.AutoField(primary_key=True, serialize=False, db_column='ID_Rol')),
                ('nombre',  models.CharField(max_length=50, unique=True, db_column='nombre')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Rol',
            },
        ),

        # ── PROVINCIA ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia',      models.AutoField(primary_key=True, serialize=False, db_column='ID_provincia')),
                ('nombre_provincia',  models.CharField(max_length=100, db_column='nombre_provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'Provincia',
            },
        ),

        # ── LOCALIDAD ─────────────────────────────────────────────────────
        # Se crea primero sin la FK, luego se agrega con AddField
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad',      models.AutoField(primary_key=True, serialize=False, db_column='ID_localidad')),
                ('codigo_postal',     models.IntegerField(db_column='codigo_postal')),
                ('nombre_localidad',  models.CharField(max_length=150, db_column='nombre_localidad')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'Localidad',
            },
        ),

        # FK Localidad → Provincia
        # db_column='id_provincia' coincide con FOREIGN KEY (id_provincia) del SQL original
        migrations.AddField(
            model_name='localidad',
            name='fk_provincia',
            field=models.ForeignKey(
                db_column='id_provincia',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='localidades',
                to='proveedores_app.provincia',
            ),
        ),

        # ── USUARIO ───────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario',        models.AutoField(primary_key=True, serialize=False, db_column='ID_Usuario')),
                ('nombre_usuario',    models.CharField(max_length=100, db_column='Nombre_Usuario')),
                ('apellido_usuario',  models.CharField(max_length=100, db_column='Apellido_Usuario')),
                ('dni',               models.IntegerField(unique=True, db_column='DNI')),
                ('correo_usuario',    models.EmailField(max_length=254, unique=True, db_column='Correo_Usuario')),
                ('contrasena',        models.CharField(max_length=128, db_column='Contrasena')),
                ('estado',            models.BooleanField(default=True, db_column='Estado')),
                # FK → Rol: db_column='ID_Rol' coincide con FOREIGN KEY (ID_Rol) del SQL original
                ('fk_rol', models.ForeignKey(
                    db_column='ID_Rol',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='usuarios',
                    to='proveedores_app.rol',
                )),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),

        # ── PROVEEDOR ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor',        models.AutoField(primary_key=True, serialize=False, db_column='ID_proveedor')),
                ('nombre_proveedor',    models.CharField(max_length=200, db_column='nombre_proveedor')),
                ('telefono',            models.CharField(blank=True, max_length=20, null=True, db_column='telefono')),
                ('correo_proveedor',    models.EmailField(blank=True, max_length=254, null=True, db_column='correo_proveedor')),
                ('cuit',                models.CharField(max_length=13, unique=True, db_column='cuit')),
                ('estado',              models.BooleanField(default=True, db_column='estado')),
                ('score_riesgo_actual', models.IntegerField(default=0, db_column='score_riesgo_actual')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),

        # ── DIRECCION ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False, db_column='ID_Direccion')),
                ('calle',        models.CharField(max_length=200, db_column='calle')),
                ('altura',       models.IntegerField(db_column='altura')),
                # FK → Proveedor: db_column='ID_proveedor' (minúscula p) igual al SQL original
                ('fk_proveedor', models.ForeignKey(
                    db_column='ID_proveedor',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='direcciones',
                    to='proveedores_app.proveedor',
                )),
                # FK → Localidad: db_column='ID_localidad' (minúscula l) igual al SQL original
                ('fk_localidad', models.ForeignKey(
                    db_column='ID_localidad',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='direcciones',
                    to='proveedores_app.localidad',
                )),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'Direccion',
            },
        ),
    ]