# Generated by Django 6.0.4 on 2026-04-20 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_postal', models.IntegerField()),
                ('nombre_localidad', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'Localidad',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto del proveedor', max_length=20, null=True)),
                ('correo_proveedor', models.EmailField(blank=True, help_text='Correo electrónico de contacto', max_length=254, null=True)),
                ('cuit', models.CharField(help_text='CUIT sin guiones, ej: 20123456789', max_length=13, unique=True)),
                ('estado', models.BooleanField(default=True, help_text='True: activo | False: dado de baja')),
                ('score_riesgo_actual', models.IntegerField(default=0, help_text='Score de riesgo 0-100. Calculado por el módulo predictivo.')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'Provincia',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=200)),
                ('altura', models.IntegerField(help_text='Número de puerta / altura de la calle')),
                ('fk_localidad', models.ForeignKey(db_column='fk_Localidad', on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='proveedores_app.localidad')),
                ('fk_proveedor', models.ForeignKey(db_column='fk_Proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='proveedores_app.proveedor')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'Direccion',
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='fk_provincia',
            field=models.ForeignKey(db_column='fk_Provincia', on_delete=django.db.models.deletion.PROTECT, related_name='localidades', to='proveedores_app.provincia'),
        ),
    ]
