# Generated by Django 6.0.4 on 2026-07-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id_propiedad', models.AutoField(db_column='ID_Propiedad', primary_key=True, serialize=False)),
                ('nombre_propiedad', models.CharField(db_column='nombre_propiedad', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'db_table': 'Propiedad',
            },
        ),
        migrations.CreateModel(
            name='PropiedadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(db_column='valor', max_length=200)),
                ('fk_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_producto', to='proveedores_app.producto')),
                ('fk_propiedad', models.ForeignKey(db_column='ID_Propiedad', on_delete=django.db.models.deletion.PROTECT, related_name='valores_productos', to='proveedores_app.propiedad')),
            ],
            options={
                'verbose_name': 'Propiedad de Producto',
                'verbose_name_plural': 'Propiedades de Productos',
                'db_table': 'Propiedad_Producto',
                'unique_together': {('fk_producto', 'fk_propiedad')},
            },
        ),
    ]
