# Generated by Django 6.0.4 on 2026-04-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_Categoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='nombre_categoria', max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='ID_Rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Rol',
            },
        ),
        migrations.AlterField(
            model_name='direccion',
            name='altura',
            field=models.IntegerField(db_column='altura'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(db_column='calle', max_length=200),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='fk_localidad',
            field=models.ForeignKey(db_column='ID_localidad', on_delete=django.db.models.deletion.PROTECT, related_name='direcciones', to='proveedores_app.localidad'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='fk_proveedor',
            field=models.ForeignKey(db_column='ID_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='proveedores_app.proveedor'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='id_direccion',
            field=models.AutoField(db_column='ID_Direccion', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='codigo_postal',
            field=models.IntegerField(db_column='codigo_postal'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='fk_provincia',
            field=models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.PROTECT, related_name='localidades', to='proveedores_app.provincia'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='id_localidad',
            field=models.AutoField(db_column='ID_localidad', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='nombre_localidad',
            field=models.CharField(db_column='nombre_localidad', max_length=150),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo_proveedor',
            field=models.EmailField(blank=True, db_column='correo_proveedor', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(db_column='cuit', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.BooleanField(db_column='estado', default=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.AutoField(db_column='ID_proveedor', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(db_column='nombre_proveedor', max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='score_riesgo_actual',
            field=models.IntegerField(db_column='score_riesgo_actual', default=0),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(db_column='telefono', max_length=20),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='id_provincia',
            field=models.AutoField(db_column='ID_provincia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre_provincia',
            field=models.CharField(db_column='nombre_provincia', max_length=100),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='ID_pedido', primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(db_column='estado_pedido', max_length=50)),
                ('fecha_emision', models.DateField(db_column='fecha_emision')),
                ('fecha_entrega_esperada', models.DateField(db_column='fecha_entrega_esperada')),
                ('fecha_entrega_real', models.DateField(blank=True, db_column='fecha_entrega_real', null=True)),
                ('fk_proveedor', models.ForeignKey(db_column='ID_proveedor', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='proveedores_app.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(db_column='ID_Factura', primary_key=True, serialize=False)),
                ('nro_factura', models.IntegerField(db_column='nro_factura')),
                ('fecha_emision', models.DateField(db_column='fecha_emision')),
                ('monto_total', models.DecimalField(db_column='monto_total', decimal_places=2, max_digits=12)),
                ('archivo_url', models.CharField(db_column='archivo_url', max_length=500)),
                ('datos_crudos_ocr', models.TextField(blank=True, db_column='datos_crudos_ocr', null=True)),
                ('estado_validacion', models.IntegerField(db_column='estado_validacion', default=0, help_text='0: pendiente | 1: validado | 2: rechazado')),
                ('fk_proveedor', models.ForeignKey(db_column='ID_proveedor', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='proveedores_app.proveedor')),
                ('fk_pedido', models.ForeignKey(db_column='ID_pedido', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='proveedores_app.pedido')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_Producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(db_column='nombre_producto', max_length=200)),
                ('fk_categoria', models.ForeignKey(db_column='ID_Categoria', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='proveedores_app.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(db_column='Nombre_Usuario', max_length=100)),
                ('apellido_usuario', models.CharField(db_column='Apellido_Usuario', max_length=100)),
                ('dni', models.IntegerField(db_column='DNI')),
                ('correo_usuario', models.EmailField(db_column='Correo_Usuario', max_length=254, unique=True)),
                ('contrasena', models.CharField(db_column='Contrasena', max_length=255)),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
                ('fk_rol', models.ForeignKey(db_column='ID_Rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='proveedores_app.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='fk_usuario',
            field=models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='proveedores_app.usuario'),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(db_column='cantidad_producto')),
                ('precio_unitario', models.DecimalField(db_column='precio_unitario', decimal_places=2, max_digits=12)),
                ('fk_pedido', models.ForeignKey(db_column='ID_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proveedores_app.pedido')),
                ('fk_producto', models.ForeignKey(db_column='ID_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='proveedores_app.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'db_table': 'Detalle_Pedido',
                'unique_together': {('fk_pedido', 'fk_producto')},
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_actual', models.FloatField(db_column='precio_actual')),
                ('stock', models.BooleanField(db_column='stock', default=True)),
                ('ultima_actualizacion', models.DateField(db_column='ultima_actualizacion')),
                ('calidad', models.IntegerField(db_column='calidad')),
                ('fk_producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_producto', to='proveedores_app.producto')),
                ('fk_proveedor', models.ForeignKey(db_column='ID_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='productos_proveedor', to='proveedores_app.proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor - Producto',
                'verbose_name_plural': 'Proveedores - Productos',
                'db_table': 'Proveedor_Producto',
                'unique_together': {('fk_proveedor', 'fk_producto')},
            },
        ),
    ]
