# Generated by Django 6.0.4 on 2026-09-25 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_app', '0002_propiedad_propiedadproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id_tipo_reporte', models.AutoField(db_column='ID_Tipo_Reporte', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(db_column='nombre_tipo', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Tipos de Reportes',
                'db_table': 'Tipo_Reporte',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(db_column='ID_Reporte', primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_column='fecha_generacion')),
                ('fecha_inicio_filtro', models.DateField(db_column='fecha_inicio_filtro')),
                ('fecha_fin_filtro', models.DateField(db_column='fecha_fin_filtro')),
                ('escala_precio', models.FloatField(blank=True, db_column='escala_precio', null=True)),
                ('escala_calidad', models.FloatField(blank=True, db_column='escala_calidad', null=True)),
                ('escala_velocidad', models.FloatField(blank=True, db_column='escala_velocidad', null=True)),
                ('recomendacion_texto', models.TextField(blank=True, db_column='recomendacion_texto', null=True)),
                ('datos_completos_snapshot', models.JSONField(db_column='datos_completos_snapshot')),
                ('fk_producto', models.ForeignKey(blank=True, db_column='ID_Producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asociados', to='proveedores_app.producto')),
                ('fk_proveedor', models.ForeignKey(blank=True, db_column='ID_Proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asociados', to='proveedores_app.proveedor')),
                ('fk_usuario', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.PROTECT, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
                ('fk_tipo_reporte', models.ForeignKey(db_column='ID_Tipo_Reporte', on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='proveedores_app.tiporeporte')),
            ],
            options={
                'verbose_name': 'Reporte de Análisis',
                'verbose_name_plural': 'Reportes de Análisis',
                'db_table': 'Reporte',
            },
        ),
    ]
